config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", registrations: 'registrations' }

  root to: "galleries#index"
  resources :galleries, :artists


  resources :galleries, only: [:show] do
    resources :paintings, only: [:index, :new, :create]
  end

  resources :artists, only: [:show] do
    resources :paintings, only: [:index]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :paintings
	has_many :artists, through: :paintings, class_name: 'User'
  validates :title, presence: true
  validates :title, uniqueness: true
  validates :city, presence: true
  validates :price, presence: true
  validates :painting_ids, presence: { message: "Please select at least one of your paintings" }


  def self.cities
    self.all.collect {|gallery| gallery.city}.uniq
  end

  def self.sort_by_city(city)
    self.where(city: city)
  end

  def self.sort_by_style(style)
    self.includes(:paintings).where(paintings: { style: style })
  end

  def painting=(painting_attributes)
    if painting_attributes[:title].present? || painting_attributes[:year].present? || painting_attributes[:style].present?
        painting = Painting.create(painting_attributes)
        self.paintings << painting
      end
  end

end

app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :artist, class_name: 'User'
	belongs_to :gallery

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :year, presence: true
  validates :style, presence: true

  def self.styles
    self.all.collect {|painting| painting.style}.uniq
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :paintings, :foreign_key => 'artist_id'
	has_many :galleries, through: :paintings


  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || root_path
  end


end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :authenticate_user!

  def index
    @artists = User.all
  end

  def show
    @artist = User.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @artist, serializer: ArtistSerializer }
    end
  end

  def edit
    @artist = User.find(params[:id])
  end

  def update
    @artist = User.find(params[:id])
    @artist.update(artist_params)
    redirect_to artist_path(@artist), :flash => { :success => "Your bio was successfully updated!" }
  end

  private
    def artist_params
      params.require(:user).permit(:bio)
    end

end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @cities = Gallery.cities
    @styles = Painting.styles
    if !params[:city].blank?
      @galleries = Gallery.sort_by_city(params[:city])
    elsif !params[:style].blank?
      @galleries = Gallery.sort_by_style(params[:style])
    else
      @galleries = Gallery.all
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @paintings = @gallery.paintings
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @paintings }
    end
  end

  def new
    @gallery = Gallery.new
    @painting = Painting.new
    @paintings = current_user.paintings
  end

  def create
    @gallery = Gallery.new(gallery_params)
    if @gallery.save
      respond_to do |format|
        format.html { redirect_to gallery_path(@gallery)}
        format.json { render json: @gallery }
      end
    else
      @paintings = current_user.paintings
      render :new
    end
  end

  private
    def gallery_params
      params.require(:gallery).permit(:title, :city, :price,
                                      painting_ids:[],
                                      :painting => [:artist_id, :title, :style, :year])
    end


end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :authenticate_user!

  def new #new_gallery_painting GET    /galleries/:gallery_id/paintings/new
    @gallery = Gallery.find_by(id: params[:gallery_id])
    if @gallery
      @painting = @gallery.paintings.build
    else
      redirect_to galleries_path, :flash => { :error => "Gallery is not found" }
    end
  end

  def create # gallery_paintings_path POST   /galleries/:gallery_id/paintings
    @gallery = Gallery.find_by(id: params[:gallery_id])
    @painting = @gallery.paintings.build(painting_params)
    if @painting.save
      redirect_to gallery_path(@gallery), :flash => { :success => "Painting was successfully added!" }
    else
      render :new
    end
  end

  def index #artist_paintings_path GET    /artists/:artist_id/paintings /galleries/:galery_id/paintings
    if params[:artist_id]
      @artist = User.find_by(id: params[:artist_id])
      @paintings = @artist.paintings
    elsif params[:gallery_id]
      @gallery = Gallery.find(params[:gallery_id])
      @paintings = @gallery.paintings
    end

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @paintings }
    end
  end

private
  def painting_params
    params.require(:painting).permit(:title, :year, :style, :artist_id)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user     
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/painting_helper.rb
module PaintingHelper
end

app/views/artists/_artist.html.erb
<h3><%= link_to artist.name, artist_path(artist) %></h3>

app/views/artists/_form.html.erb
<%= form_for @artist, url: artist_path, :method => "patch" do |f| %>
  <%= f.label :bio %> <br>
  <%= f.text_area :bio %> <br>
  <%= f.submit "Update Bio" %>
<% end %>

app/views/artists/edit.html.erb
<%= render 'artists/form'%> 

app/views/artists/index.html.erb
<%= render :partial => "artist", :collection => @artists %>

app/views/artists/show.html.erb
<div class="artist-container">
  <%= link_to "Next Artist", '#', :class=>"js-next", "data-id" => "#{@artist.id}" unless @artist == User.last %>
  <h3 class="artistName" data-id="#{@artist.id}"><%= @artist.name %></h3>
  <%= link_to "#{@artist.name} paintings", artist_paintings_path(@artist), :class=>"js-artist-paintings", "data-id" => "#{@artist.id}" if @artist.paintings.any? %>
  <div class="painting-container"></div>
  <p class="artistBio"><%= @artist.bio if @artist.bio != nil%></p>
</div>

<%= link_to 'Add Bio', edit_artist_path(@artist), { :class=>"button add-bio" } if @artist == current_user && @artist.bio == nil%>
<%= link_to 'Edit Bio', edit_artist_path(@artist), :class=>"edit-bio" if @artist == current_user && @artist.bio%> <br>

<script id="painting-template" type="text/x-handlebars-template">
  <dl class="painting-info">
      <dt class="p-title">{{title}}</dt>
      <dd class="p-style">{{style}}</dd>
      <dd class="p-year">{{year}}</dd>
  </dl> 
</script>

<script id="artist-info-template" type="text/x-handlebars-template">
  <a class="js-next" data-id="{{id}}" href="#">Next Artist</a>
  <h3 class="artistName" data-id="{{id}}">{{name}}</h3>
  <a class="js-artist-paintings" data-id="{{id}}" href="/artists/{{id}}/paintings">{{name}} paintings</a>
  <div class="painting-container"></div>
  <p class="artistBio">{{bio}}</p>
</script>

app/views/galleries/_filter.html.erb
<div>
  <h3>Filter galleries</h3>
  <%= form_tag("/galleries", method: "get") do %>
    <%= label_tag "by city" %>
    <%= select_tag "city", options_for_select(@cities), include_blank: true %> <br>
    <%= label_tag "or by style" %>
    <%= select_tag "style", options_for_select(@styles), include_blank: true %>
    <%= submit_tag "Filter" %>
  <% end %>
  <%= link_to  "Reset filter", root_path if params[:commit]%>
</div>

app/views/galleries/_gallery.html.erb
<h3><%= link_to gallery.title, gallery_path(gallery) %> <%= "(#{gallery.city})" %></h3>
<ul>
  <% gallery.artists.uniq.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>

app/views/galleries/index.html.erb
<%= link_to 'Create a New Gallery', new_gallery_path, { :class=>"button" } %>

<%= render 'galleries/filter' %>

<%= render @galleries %>

app/views/galleries/new.html.erb
<h1>New Gallery</h1>

<%= render partial: 'layouts/valid_errors', locals: {object: @gallery}%>

<%= form_for @gallery, html: {class: "js-new-gallery-form"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :city %>
  <%= f.text_field :city %> <br>
  <%= f.label :price %>
  <%= f.number_field :price %> <br>

  <%= content_tag(:p, "Select your paintings, which you would like to present") if current_user.paintings.any? %>
  <%= f.collection_check_boxes :painting_ids, @paintings, :id, :title %> <br>

  <%= render partial: 'layouts/valid_errors', locals: {object: @gallery.paintings.build}%>

  <%= content_tag(:p, "Add a new painting") %>
  <%= f.fields_for @gallery.paintings.build do |p| %>
    <%= p.hidden_field :artist_id, :value => current_user.id %>
    <%= p.label :title %>
    <%= p.text_field :title %> <br>
    <%= p.label :style %>
    <%= p.text_field :style %> <br>
    <%= p.label :year %>
    <%= p.number_field :year %> <br>
  <% end %>

  <%= f.submit data: { disable_with: false } %>
<% end %>

<div class="new-gallery"></div>

<script id="new-gallery-template" type="text/x-handlebars-template">
  <h2 class="galleryTitle">{{title}}</h2>
  <h3 class="galleryCity">{{city}}</h3>
  <h3 class="galleryPrice">Price: ${{price}}</h3>
  <a class="js-now-at-gallery" data-id="{{id}}" href="#">At this gallery you can see...</a>
  <p>
  <ul class="now-at-gallery-ul"></ul>
</script>

<script id="now-at-gallery-template" type="text/x-handlebars-template">
      <li class="painting-title"><strong>{{title}}</strong> by {{artistName}}</li>
</script>

app/views/galleries/show.html.erb
<h2><%= @gallery.title %></h2>
<h3>Location: <%=  @gallery.city%></h3>
<h3>Price: <%=  "$#{@gallery.price}"%></h3>
<%= link_to 'At this gallery you can see...', new_gallery_painting_path(@gallery), :class=>"js-now-at-gallery", "data-id" => "#{@gallery.id}"if @gallery.artists.present?%>
<p>

<ul class="now-at-gallery-ul"></ul>

<%= link_to 'Add Painting to Gallery', new_gallery_painting_path(@gallery), { :class=>"button" } %>

<script id="now-at-gallery-template" type="text/x-handlebars-template">
      <li class="painting-title"><strong>{{title}}</strong> by {{artistName}}</li>
</script>

app/views/layouts/_header.html.erb
<p id="signed-in-as"><%= "Signed in as #{current_user.name}" if user_signed_in? %></p>

<nav>
  <ul>
    <li><%= link_to  "Home", root_path %></li>
    <li><%= link_to  "Artists", artists_path if user_signed_in?%></li>
    <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete if user_signed_in?%></li>
    <li><%= link_to "Log in", new_user_session_path if !user_signed_in?%></li>
    <li><%= link_to "Sign up", new_user_registration_path if !user_signed_in?%></li>
    <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path if !user_signed_in?%></li>
  </ul>
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_valid_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Art Galleries Navigator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Rozha+One|Arvo:700" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body data-user="<%= current_user.id if current_user %>" data-last-user="<%= User.last.id %>">
  <div class="wrapper">

        <h1 id='logo'>Art Galleries Navigator</h1>
        <%= render 'layouts/header' %>
        <%= render 'layouts/messages' %>
        <%= yield %>


    <footer class="branding">
      <small>&copy; 2017 <strong>Art Galleries Navigator</strong></small>
    </footer>
  </div>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/4.0.11/handlebars.min.js"></script>

  <!--[if lt IE 7]>
    <script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
    <script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
  <![endif]-->
</body>
</html>

app/views/paintings/_errors.html.erb
<% if @painting.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @painting.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/paintings/_painting.html.erb
<dl>
    <dt><%= "'#{painting.title}'" %></dt>
    <dd><%= painting.style %></dd>
    <dd><%= painting.year %></dd>
    <p>
</dl>

app/views/paintings/index.html.erb
<%= render :partial => "painting", :collection => @paintings %>

app/views/paintings/new.html.erb
<h2>Form for a new painting for <%= @gallery.title%>:</h2>

<%= render partial: 'layouts/valid_errors', locals: {object: @painting}%>

<%= form_for @painting, url: gallery_paintings_path(@gallery) do |f| %>
  <%= f.hidden_field(:artist_id, :value => current_user.id)%>
  <%= f.label :title %>
  <%= f.text_field :title %> <br>
  <%= f.label :year %>
  <%= f.number_field :year %><br>
  <%= f.label :style %>
  <%= f.text_field :style %> <br>
  <br>
  <%= f.submit "Add Painting", { :class=>"button" } %>
<% end %>